# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klony', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acers',
            name='new_image_bark',
            field=models.ImageField(blank=True, null=True, upload_to='bark'),
        ),
        migrations.AlterField(
            model_name='acers',
            name='new_image_leaf',
            field=models.ImageField(blank=True, null=True, upload_to='leaf'),
        ),
        migrations.AlterField(
            model_name='acers',
            name='new_image_tree',
            field=models.ImageField(blank=True, null=True, upload_to='tree'),
        ),
    ]
