# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klony', '0002_auto_20170118_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acers',
            name='bark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='botanic_name',
            field=models.CharField(blank=True, max_length=113),
        ),
        migrations.AlterField(
            model_name='acers',
            name='characteristics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='flowers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='frost_res',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='frost_res_zones',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='fruits',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='height_10',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='image_bark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='image_leaf',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='image_tree',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='in_poland',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='latin_name',
            field=models.CharField(blank=True, max_length=113),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_autumn1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_autumn2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_spring1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_spring2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_summer1',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_summer2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='leaf_size',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='leaf_structure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='leaf_tail',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='occurrence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='origin1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='origin2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='other_botanic_name1',
            field=models.CharField(blank=True, max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='other_botanic_name2',
            field=models.CharField(blank=True, max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='other_latin_name',
            field=models.CharField(blank=True, max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='other_names',
            field=models.CharField(blank=True, max_length=113, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='other_variant',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='shape1',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='shape2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='soil_kind',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='soil_ph',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='stand',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='variant',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
