# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klony', '0003_auto_20170118_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acers',
            name='frost_res',
            field=models.TextField(blank=True, choices=[('całkowicie mrozoodporny', 'całkowicie mrozoodporny'), ('mrozoodporny', 'mrozoodporny'), ('nie w pełni odporny - przemarza podczas surowych zim', 'nie w pełni odporny - przemarza podczas surowych zim')], null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_autumn1',
            field=models.CharField(blank=True, choices=[('zielony', 'zielony'), ('czerwony', 'czerwony'), ('żółty', 'żółty'), ('pomarańczowy', 'pomarańczowy'), ('pstry', 'pstry')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_spring1',
            field=models.CharField(blank=True, choices=[('zielony', 'zielony'), ('czerwony', 'czerwony'), ('żółty', 'żółty'), ('pomarańczowy', 'pomarańczowy'), ('pstry', 'pstry')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='lc_summer1',
            field=models.CharField(blank=True, choices=[('zielony', 'zielony'), ('czerwony', 'czerwony'), ('żółty', 'żółty'), ('pomarańczowy', 'pomarańczowy'), ('pstry', 'pstry')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='origin1',
            field=models.CharField(blank=True, choices=[('AS', 'Azja'), ('EU', 'Europa'), ('NA', 'Ameryka Płn.')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='acers',
            name='shape1',
            field=models.CharField(blank=True, choices=[('drzewo', 'drzewo'), ('krzew', 'krzew'), ('niewysokie drzewo', 'niewysokie drzewo'), ('niewysokie drzewo lub krzew', 'niewysokie drzewo lub krzew')], max_length=90, null=True),
        ),
    ]
