# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klony', '0006_auto_20170205_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acers',
            name='image_bark',
            field=models.ImageField(blank=True, null=True, upload_to='tx_acers'),
        ),
        migrations.AlterField(
            model_name='acers',
            name='image_leaf',
            field=models.ImageField(blank=True, null=True, upload_to='tx_acers'),
        ),
        migrations.AlterField(
            model_name='acers',
            name='image_tree',
            field=models.ImageField(blank=True, null=True, upload_to='tx_acers'),
        ),
    ]
